apiVersion: v1
kind: Service
metadata:
  name: form-service
  labels:
    run: form
spec:
  selector:
    app: form
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
